name: D

on:
  push:
    branches: [ master ]
    paths:
    - 'src/*'
    - 'demo/*'
    - 'data/*'
    - 'dub.json'
    - '.github/workflows/*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dc: [dmd-latest, ldc-latest, dmd-2.094.2, ldc-1.24.0]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7
      with:
        compiler: ${{ matrix.dc }}
    - name: 'Build & Test'
      run: dub build --compiler=$DC
